# Generated by Django 5.0.6 on 2024-05-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atom",
            fields=[
                (
                    "atomic_number",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("symbol", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=20)),
                ("atomic_weight", models.FloatField()),
                ("atomic_weight_sd", models.FloatField(blank=True, null=True)),
                ("configuration", models.CharField(max_length=32)),
                ("inchi", models.CharField(max_length=11)),
                ("inchikey", models.CharField(max_length=27)),
            ],
            options={
                "db_table": "chem_atom",
            },
        ),
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k", models.CharField(db_column="k", max_length=100)),
                ("fk", models.CharField(db_column="fk", max_length=100)),
                ("species_type", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "chem_index",
            },
        ),
        migrations.CreateModel(
            name="Molecule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stoichiometric_formula", models.CharField(max_length=40)),
                ("ordinary_formula", models.CharField(max_length=80, unique=True)),
                ("charge", models.SmallIntegerField()),
                ("inchi", models.CharField(blank=True, max_length=200)),
                ("inchikey", models.CharField(blank=True, max_length=27)),
                ("cml", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=80, unique=True)),
                ("names", models.CharField(blank=True, max_length=2000)),
            ],
            options={
                "db_table": "chem_molecule",
            },
        ),
        migrations.CreateModel(
            name="Ion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge", models.SmallIntegerField()),
                ("inchi", models.CharField(max_length=20)),
                ("inchikey", models.CharField(max_length=27)),
                (
                    "atom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chem.atom"
                    ),
                ),
            ],
            options={
                "db_table": "chem_ion",
            },
        ),
        migrations.CreateModel(
            name="Isotope",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mass_number", models.IntegerField()),
                ("symbol", models.CharField(max_length=5)),
                ("ram", models.FloatField()),
                ("ram_sd", models.FloatField(blank=True, null=True)),
                ("abundance", models.FloatField()),
                ("abundance_sd", models.FloatField(blank=True, null=True)),
                ("inchi", models.CharField(max_length=11)),
                ("inchikey", models.CharField(max_length=27)),
                ("nucspin", models.FloatField()),
                (
                    "atom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chem.atom"
                    ),
                ),
            ],
            options={
                "db_table": "chem_isotope",
            },
        ),
        migrations.CreateModel(
            name="IsotopeIon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge", models.SmallIntegerField()),
                ("inchi", models.CharField(max_length=20)),
                ("inchikey", models.CharField(max_length=27)),
                (
                    "isotope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chem.isotope"
                    ),
                ),
            ],
            options={
                "db_table": "chem_isotope_ion",
            },
        ),
        migrations.CreateModel(
            name="Isotopologue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stoichiometric_formula", models.CharField(max_length=80)),
                ("ordinary_formula", models.CharField(max_length=160, unique=True)),
                ("charge", models.SmallIntegerField()),
                ("inchi", models.CharField(blank=True, max_length=200)),
                ("inchikey", models.CharField(blank=True, max_length=27)),
                ("abundance", models.FloatField(blank=True, null=True)),
                ("cml", models.TextField(blank=True, null=True)),
                ("slug", models.CharField(max_length=160, unique=True)),
                ("point_group", models.CharField(blank=True, max_length=5)),
                (
                    "molecule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chem.molecule"
                    ),
                ),
            ],
            options={
                "db_table": "chem_isotopologue",
            },
        ),
    ]
