# Generated by Django 3.2.20 on 2023-09-27 18:00

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'chem_molecule',
            },
        ),
        migrations.CreateModel(
            name='Isotopologue',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('formula', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('dataset', models.CharField(max_length=200, null=True, unique=True)),
                ('abundance', models.FloatField(blank=True, default=1, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('molecule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chem.molecule')),
            ],
            options={
                'db_table': 'chem_isotopologue',
            },
        ),
    ]
