# Generated by Django 5.0.6 on 2024-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ion",
            name="atom",
        ),
        migrations.RemoveField(
            model_name="isotope",
            name="atom",
        ),
        migrations.DeleteModel(
            name="Index",
        ),
        migrations.RemoveField(
            model_name="isotopeion",
            name="isotope",
        ),
        migrations.AddField(
            model_name="isotopologue",
            name="html",
            field=models.CharField(default="XXX", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="isotopologue",
            name="mass",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="molecule",
            name="html",
            field=models.CharField(default="XXX", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="molecule",
            name="mass",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="isotopologue",
            table=None,
        ),
        migrations.AlterModelTable(
            name="molecule",
            table=None,
        ),
        migrations.DeleteModel(
            name="Ion",
        ),
        migrations.DeleteModel(
            name="Atom",
        ),
        migrations.DeleteModel(
            name="Isotope",
        ),
        migrations.DeleteModel(
            name="IsotopeIon",
        ),
    ]
