# Generated by Django 4.2.11 on 2026-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the update.')),
                ('title', models.CharField(default='Update', help_text='The title of the update.', max_length=200)),
                ('content', models.TextField(help_text='The update message.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
