# Generated by Django 4.2.11 on 2026-02-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteupdate',
            options={'ordering': ['date', 'id']},
        ),
    ]
