# Generated by Django 4.2.11 on 2026-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_siteupdate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Mark this update as important to highlight it on the website.'),
        ),
    ]
