# Django-related settings
# the base directory (full path)
#  填写crm项目的第一层绝对路径
chdir           = /home/jingxin/ExoMolHR-web/exomolhr
# Django's wsgi file
# 填写crm项目第二层的相对路径，找到第二层目录下的wsgi.py
# 这里填写的不是路径，是以上一个参数为相对，找到第二层项目目录下的wsgi.py文件
# module          = /exomolhr/exomolhr/wsgi.py
wsgi-file       = exomolhr/exomolhr/wsgi.py
# the virtualenv (full path)
# 填写虚拟环境解释器的第一层工作目录 
# home            = /opt/tf_crm/venv_crm
# process-related settings
# master
master          = true
# maximum number of worker processes
# 代表定义uwsgi运行的多进程数量，官网给出的优化建议是 2*cpu核数+1 ，单核的cpu填写几?
# 如果是单进程，十万个请求，都丢给一个进程去处理
# 4个工作进程，十万个请求，就分给了4个进程去分摊处理
processes       = 4
threads         = 2

# the socket (use the full path to be safe
# 这里的socket参数，是用于和nginx结合部署的unix-socket参数，这里临时先暂停使用
socket          = 127.0.0.1:8888
#  线上不会用http参数，因为对后端是不安全的，使用socket参数是安全的连接，用nginx反向代理去访问
# 后端程序是运行在防火墙内部，外网是无法直接访问的
# 临时使用http参数，便于我们用浏览器调试访问
# http            = 127.0.0.1:8888

# ... with appropriate permissions - may be needed
# chmod-socket    = 664
# clear environment on exit
vacuum          = true

pidfile         = uwsgi.pid
deamonize       = uwsgi.log
