# Generated by Django 3.2.20 on 2023-09-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeTable',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('molecule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chem.molecule')),
            ],
        ),
        migrations.CreateModel(
            name='Linelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu', models.FloatField()),
                ('unc', models.FloatField()),
                ('A', models.FloatField()),
                ('S', models.FloatField()),
                ('Epp', models.FloatField()),
                ('gp', models.PositiveSmallIntegerField()),
                ('gpp', models.PositiveSmallIntegerField()),
                ('Jp', models.PositiveSmallIntegerField(null=True)),
                ('Jpp', models.PositiveSmallIntegerField(null=True)),
                ('qnp', models.CharField(max_length=500)),
                ('qnpp', models.CharField(max_length=500)),
                ('prms_json', models.TextField(null=True)),
                ('isotopologue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chem.isotopologue')),
            ],
        ),
    ]
