# Generated by Django 5.0.6 on 2024-05-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QNs", models.CharField(max_length=512)),
                ("csv_filename", models.CharField(max_length=72)),
                (
                    "isotopologue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chem.isotopologue",
                    ),
                ),
            ],
        ),
    ]
