# Generated by Django 5.0.6 on 2024-05-13 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("linelist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hrmeta",
            old_name="csv_filename",
            new_name="data_filename",
        ),
    ]
