# Generated by Django 5.0.6 on 2024-05-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linelist", "0002_rename_csv_filename_hrmeta_data_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrmeta",
            name="QNs",
            field=models.TextField(),
        ),
    ]
