# Generated by Django 5.0.6 on 2024-10-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linelist", "0003_alter_hrmeta_qns"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrmeta",
            name="numax",
            field=models.FloatField(default=100000),
        ),
    ]
