# Generated by Django 5.0.6 on 2024-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linelist", "0004_hrmeta_numax"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrmeta",
            name="numin",
            field=models.FloatField(default=0),
        ),
    ]
