# Generated by Django 4.2.11 on 2026-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist', '0005_hrmeta_numin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the update.')),
                ('content', models.TextField(help_text='The update message.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
