# Generated by Django 4.2.11 on 2026-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linelist', '0006_siteupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdate',
            name='title',
            field=models.CharField(default='Update', help_text='The title of the update.', max_length=200),
        ),
    ]
