# Generated by Django 4.2.11 on 2026-02-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linelist', '0007_siteupdate_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUpdate',
        ),
    ]
